#!/system/bin/sh
sleep 15
magisk --sqlite "REPLACE INTO settings (key,value) VALUES('denylist','1');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.bcp.innovacxion.yapeapp','com.bcp.innovacxion.yapeapp');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.bcp.innovacxion.yapeapp','com.bcp.innovacxion.yapeapp:pushservice');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.bcp.bo.wallet','com.bcp.bo.wallet');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.bcp.bo.wallet','com.bcp.bo.wallet:dynatrace_replay_service');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.bcp.bank.bcp','com.bcp.bank.bcp');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.mooveit.bcpb','com.mooveit.bcpb');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('pe.com.interbank.mobilebanking','pe.com.interbank.mobilebanking');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('pe.com.interbank.mpay.customer','pe.com.interbank.mpay.customer');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.bbva.nxt_peru','com.bbva.nxt_peru');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('isolated','com.bbva.nxt_peru:magiskProcess:com.bbva.ethermobilesdk.devicechecker.magisk.service.MagiskService');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('isolated','com.bbva.nxt_peru:rootProcess:com.bbva.ethermobilesdk.devicechecker.root.service.RootService');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('pe.com.scotiabank.blpm.android.client','pe.com.scotiabank.blpm.android.client');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('pe.com.banbif.bancamovil','pe.com.banbif.bancamovil');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.financiero.mobile','com.financiero.mobile');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('pe.com.bn.app.bancodelanacion','pe.com.bn.app.bancodelanacion');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms.feedback');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms.learning');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms.persistent');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms.remapping1');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms.room');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms.ui');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms.unstable');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms:car');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms:identitycredentials');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.google.android.gms','com.google.android.gms:snet');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('isolated','com.google.android.gms:com.google.android.gms.chimera.IsolatedBoundBrokerService');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.android.vending','com.android.vending');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.android.vending','com.android.vending:background');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.android.vending','com.android.vending:instant_app_installer');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.android.vending','com.android.vending:quick_launch');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.android.vending','com.android.vending:recovery_mode');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('isolated','com.android.vending:com.google.android.finsky.verifier.apkanalysis.service.ApkContentsScanService');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.netflix.mediaclient','com.netflix.mediaclient');"
magisk --sqlite "REPLACE INTO denylist (package_name, process) VALUES('com.paypal.android.p2pmobile','com.paypal.android.p2pmobile');"
